### ISSUE TITLE
Unable to install using Unity 2019.2.4f1

### ISSUE THREAD

**Issue by jvdnbus** [fluviofx/fluviofx#26]
I'm trying to install the package (by adding it to the manifest.json) but Unity throws a bunch of errors. As suggested, I tried the Tools -> FluvioFX -> Install but this throws an exception as well.

Here it is:
```
ArgumentNullException: Value cannot be null.
Parameter name: type
Thinksquirrel.FluvioFX.Editor.ReflectionHelpers.Invoke[T] (System.Type type, System.String methodName, Thinksquirrel.FluvioFX.Editor.Parameter[] parameters) (at Library/PackageCache/com.thinksquirrel.fluviofx@f150f5d84b26a98ef5a03a899154b2ad085167af/ReflectionHelpers/ReflectionHelpers.cs:275)
Thinksquirrel.FluvioFX.Editor.FluvioFXInstall.GetPackagePath (System.String pkgName) (at Library/PackageCache/com.thinksquirrel.fluviofx@f150f5d84b26a98ef5a03a899154b2ad085167af/Install/FluvioFXInstall.cs:262)
Thinksquirrel.FluvioFX.Editor.FluvioFXInstall.Install (System.Boolean force) (at Library/PackageCache/com.thinksquirrel.fluviofx@f150f5d84b26a98ef5a03a899154b2ad085167af/Install/FluvioFXInstall.cs:126)
Thinksquirrel.FluvioFX.Editor.FluvioFXInstall.InstallFluvioFX () (at Library/PackageCache/com.thinksquirrel.fluviofx@f150f5d84b26a98ef5a03a899154b2ad085167af/Install/FluvioFXInstall.cs:119)
```

I am on Windows using Unity 2019.2.4f1. I have the VEG package (6.9.1) installed.

Any help would be appreciated, thank you.

**Comment by hallidev** [comment]
Running into the same issue here

**Comment by lmontoute** [comment]
@hallidev @Barbelot Check out #28 and let me know if this works for you in 2019.2!

Be aware that it may cause wonkiness with older graphs. As always, back up your graphs before upgrading!

**Comment by Barbelot** [comment]
It's installing perfectly with 2019.2.5f1. Thanks a lot, can't wait to play with it now !
