### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by MostHated** [fluviofx/fluviofx#31]
Hey there,
    I have been looking for a way to try and achieve some nice looking and fairly realistic-looking blood effects in the HDRP. I love the gif demos and such I have seen, but I am not 100% on the use cases in which this system would be ideal, though. Would digging into FluvioFX end up helping me achieve a gory blood squirt/flow/spray by chance or is that not the type of thing the package is used for?

Thanks!
-MH

**Comment by lmontoute** [comment]
Hey @MostHated,

That's definitely a valid use case for FluvioFX! You can get real simulated blood animations fairly easily. One caveat might be with blending the blood particles together to make a liquid visual. Unlike the older Fluvio package, we rely on Unity for all rendering with FluvioFX. Unity's VFX graph doesn't have a liquid renderer yet, so your mileage may vary based on how big you make your particles. Still, I'd give it a try on a fresh project and see what you can make!
