### ISSUE TITLE
Bug report: a moving collider will cause a incorrect force caculation.

### ISSUE THREAD

**Issue by haosizheng** [fluviofx/fluviofx#33]
if i make a Sphere moving through my fluid, sometimes the fluid particles got a very huge speed and splash.
And i try to fix it in computeshader but i didn't find it.

**Comment by lmontoute** [comment]
Hm, do you have a good case to reproduce or a video?

**Comment by lmontoute** [comment]
Hm, do you have a good case to reproduce or a video?

**Comment by lmontoute** [comment]
Likely related to #44, so closing for now.

**Comment by haosizheng** [comment]
thank you and sorry for did not reply.
