### ISSUE TITLE
Is the simulation done on CPU or GPU?

### ISSUE THREAD

**Issue by StickeydM** [fluviofx/fluviofx#34]
Hey. The question is in the header. 

I remember you did GPU accelerated simulation with older fluvio. This newer version works with VFX graph, which is GPU-limited, but it seems to still burn some CPU cycles. Is it done via GPU or CPU?

If on CPU, is it faster than older GPU-accelerated Fluvio?

**Comment by lmontoute** [comment]
This is GPU simulation. There's some CPU overhead as part of the VFX graph (sending initial data to the GPU and such), but all simulation is calculated on the GPU.

It's _much_, _much_ faster as well. Older Fluvio versions had to sync back up with the CPU every frame, whereas FluvioFX does not need to do this.
