### ISSUE TITLE
How to scale the simulation?

### ISSUE THREAD

**Issue by StickeydM** [fluviofx/fluviofx#37]
I don't understand how to scale simulation. Reducing density doesn't seem to help. My scene is much bigger and I want particles to be bigger, even though simulation is the same. How to do it?

**Comment by lmontoute** [comment]
There are two options:

(This one's a bit tricky, but more accurate and definitely possible) You'll need to increase the smoothing distance, and also tweak the other parameters to match. Scaling fluid simulation is always going to be tough if you are unfamiliar with how each property works.

(This one is easier in theory, but less accurate and I'm unsure if possible) You might be able to modify the position of the particles after simulation is done before rendering and then set them back for the next frame. That would let you scale things up or down.
