### ISSUE TITLE
Flamethrower Example

### ISSUE THREAD

**Issue by baughbj** [fluviofx/fluviofx#39]
Hello,

This isn't necessarily a bug with the package, but I was wondering if it would be possible to provide an example of a flamethrower using fluvio, like the video example below:

https://www.youtube.com/watch?v=PeNe3QVZ_Yo&list=WL&index=2&t=0s

**Comment by lmontoute** [comment]
At the moment, I haven't made the examples available due to a lot of fluctuation in the API (they've been breaking so I'd have to recreate them each time).

Things are a little stable, so once my schedule gets better I can look into uploading the examples.
