### ISSUE TITLE
Unity 2019.3 Support

### ISSUE THREAD

**Issue by djspider117** [fluviofx/fluviofx#40]
Hi! I've seen in a prev issue that 2019.3 will be coming and I can relate to having things from work derail plans. To that end, I tried figuring out myself what I can do to at least make it work.

If you remove capacity from the shader preprocesor and keep just
`#define FLUVIO_MAX_GRID_SIZE {(uint)Mathf.Pow(262144, 1.0f / 3.0f)}`

I thought maybe that could work. Unfortunately it did now. Amongst the first issue I encountered was:
![image](https://user-images.githubusercontent.com/20155221/82104260-dc5b3780-971e-11ea-82bc-015782c1c810.png)

Looking into the generated code:

![image](https://user-images.githubusercontent.com/20155221/82104284-f137cb00-971e-11ea-8f91-667dc79801d7.png)

I'd love to help on this but I'm new to the inner workings of VFX graph. If you know something of the top of your head I could investigate more.

**Comment by lmontoute** [comment]
It looks like Unity has changed the various values (mass, size, age, lifetime, etc.) to be under an attributes object. In the shader generation code for the InitializeSolver function, you'd probably want to replace those to just refer to mass, size, age, age lifetime, etc. Or take a look at some of their shaders and update the FluvioFX shaders to match (that might be the better route)

**Comment by landonth** [comment]
@djspider117 FYI, this is a duplicate issue, Please see issue #29 for progress updates.

**Comment by lmontoute** [comment]
Closing as duplicate
