### ISSUE TITLE
Unity Recorder turns simulation unstable

### ISSUE THREAD

**Issue by kosowski** [fluviofx/fluviofx#48]
Hi! I’ve been unable to create video captures using Unity Recorder. As soon as recording starts, the simulation becomes unstable and particles are expelled in all directions. I guess this is due to long or variable frame times when recording.
Is there anything I can do to solve this?
Can the solver be forced to use an external clock? Maybe setting a constant delta time independent of game time could keep the simulation stable.

Thanks a lot, Fluvio is amazing!

**Comment by lmontoute** [comment]
This is due to #24, so we'll want to track that there. I believe it may finally be fixable with the current VFX graph, though!
